config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  resources :eventos
  resources :artigos
  devise_for :users
  
  get '/medic/newarticle', to: 'pages#medicnewarticle', as: 'medic'
  get '/medic/allarticles', to: 'pages#medicallarticles'
  get '/login', to: 'pages#login'
  get '/sobre', to: 'pages#aboutus'
  get '/medico/:id', to: 'pages#doctor'
  get '/servicos', to: 'pages#services'
  get '/medicos', to: 'pages#medicos'
  get '/galeria', to: 'pages#galeria'


  root to: "pages#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artigo.rb
class Artigo < ApplicationRecord
  extend FriendlyId
  mount_uploader :capa, CapaUploader

  belongs_to :user, optional: true
  friendly_id :titulo, use: :slugged

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/evento.rb
class Evento < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "medic"
    end
  end

  def set_admin_locale
    I18n.locale = 'pt-BR'
  end  

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || medic_path
  end

  def authenticate2_user!
    if user_signed_in?
      
    else
      redirect_to login_path, :notice => 'if you want to add a notice'
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:nome, :avatar, :email, :especialidade, :crm, :sobre, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :avatar, :email, :especialidade, :crm, :sobre, :password, :password_confirmation])
  end
end

app/controllers/artigos_controller.rb
class ArtigosController < ApplicationController
  before_action :set_artigo, only: [:show, :edit, :update, :destroy]

  # GET /artigos
  # GET /artigos.json
  def index
    @artigos = Artigo.all.reverse_order
  end

  # GET /artigos/1
  # GET /artigos/1.json
  def show
  end

  # GET /artigos/new
  def new
    @artigo = Artigo.new
  end

  # GET /artigos/1/edit
  def edit
  end

  # POST /artigos
  # POST /artigos.json
  def create
    @artigo = Artigo.new(artigo_params)
    @artigo.user_id = current_user.id

    respond_to do |format|
      if @artigo.save
        auth = {
          cloud_name: "flampic",
          api_key:    '333169189687311',
          api_secret: "kqXVte1LTbMllETzF9MySTOHUds"
        }
        @cloudUp = Cloudinary::Uploader.upload(@artigo.capa.path, auth)
        @artigo.cloudname = @cloudUp["public_id"]
        @artigo.save
        format.html { redirect_to @artigo, notice: 'Artigo criado com sucesso.' }
        format.json { render :show, status: :created, location: @artigo }
      else
        format.html { render :new }
        format.json { render json: @artigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artigos/1
  # PATCH/PUT /artigos/1.json
  def update
    respond_to do |format|
      if @artigo.update(artigo_params)
        format.html { redirect_to @artigo, notice: 'Artigo atualizado.' }
        format.json { render :show, status: :ok, location: @artigo }
      else
        format.html { render :edit }
        format.json { render json: @artigo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artigos/1
  # DELETE /artigos/1.json
  def destroy
    @artigo.destroy
    respond_to do |format|
      format.html { redirect_to artigos_url, notice: 'Artigo excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artigo
      @artigo = Artigo.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artigo_params
      params.require(:artigo).permit(:titulo, :texto, :user_id, :capa, :cloudname)
    end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:inicio, :fim, :nome, :texto)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    before_action :authenticate2_user!, only: [:medicadmin, :medicallarticles, :medicnewarticle]
    def index
        @artigos = Artigo.all
        @users = User.all
    end

    def medicnewarticle
        @artigo = Artigo.new
        render layout: "medic"
    end

    def medicallarticles
        @artigos = Artigo.where(user_id: current_user.id)
        render layout: "medic"
    end

    def aboutus
    end

    def galeria
    end

    def services
    end

    def medicos
    end

    def login
        render layout: "login"
    end

    def register
        render layout: "register"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artigos_helper.rb
module ArtigosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/artigos/_form.html.erb
<%= simple_form_for(@artigo) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <%= f.input :texto %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/artigos/edit.html.erb
<h1>Editing Artigo</h1>

<%= render 'form', artigo: @artigo %>

<%= link_to 'Show', @artigo %> |
<%= link_to 'Back', artigos_path %>

app/views/artigos/index.html.erb
   <!--med_tittle_section-->
    <div class="med_tittle_section">
        <div class="med_img_overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="med_tittle_cont_wrapper">
                        <div class="med_tittle_cont">
                            <h1>Artigos</h1>
                            <ol class="breadcrumb">
                                <li><a href="index.html">Home</a>
                                </li>
                                <li>artigos</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- med_tittle_section End -->

	<!--blog category section start-->
	<div class="blog_section med_toppadder100 med_bottompadder100">
        <div class="container">
            <div class="row">
                <div class="blog_category_main_wrapper">
                    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                        <div class="row">
                            <% if (@artigos.blank?) then %>              
                                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12 col-lg-offset-2">
                                    <b><i>Carregando artigos...</i></b>                     
                                </div>
                            <% else %> 
                                <% @artigos.each do |artigo| %>
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="blog_about">
                                            <div class="blog_img blog_post_img">
                                                <figure>
                                                    <%= cl_image_tag(artigo.cloudname, :width => 849, :height => 450) %>
                                                </figure>
                                        </div>
                                        <div class="blog_comment">
                                            <ul>
                                                <li><a href=""><i class="fa fa-comment" aria-hidden="true"></i>50</a></li>
                                            </ul>
                                        </div>
                                        <div class="blog_txt">
                                            <h1><a href="#"><%= artigo.titulo %></a></h1>
                                            <div class="blog_txt_info">
                                                <ul>
                                                    <li><%= artigo.user.nome %></li>
                                                    <li><%= artigo.created_at.strftime('%d/%m/%Y') %></li>
                                                </ul>
                                            </div>
                                            <p><%= truncate(artigo.texto, length: 350, omission: '...', escape: false) %></p>
                                                <%= link_to 'Leia Mais', artigo %>						
                                            </div>
                                        </div>
                                    </div>
                                <% end %>
                            <% end %>    
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="contect_form_blog">
                                    <input type="text" placeholder="pesquisar"><a href=""><i class="fa fa-search" aria-hidden="true"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<!--blog category section end-->

app/views/artigos/new.html.erb
<h1>New Artigo</h1>

<%= render 'form', artigo: @artigo %>

<%= link_to 'Back', artigos_path %>

app/views/artigos/show.html.erb
    <!--med_tittle_section-->
    <div class="med_tittle_section">
        <div class="med_img_overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="med_tittle_cont_wrapper">
                        <div class="med_tittle_cont">
                            <h1>Artigos</h1>
                            <ol class="breadcrumb">
                                <li><a href="index.html">Home</a>
                                </li>
                                <li>artigo</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- med_tittle_section End -->
    <!--blog category section start-->
    <div class="blog_section med_toppadder100 med_bottompadder100">
        <div class="container">
            <div class="row">
                <div class="blog_category_main_wrapper">
                    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="blog_about">
                                    <div class="blog_img blog_post_img">
                                        <figure>
											<%= cl_image_tag(@artigo.cloudname, :width => 849, :height => 450) %>
                                        </figure>
                                    </div>
                                    <div class="blog_comment">
                                        <ul>
                                            <li><a href=""><i class="fa fa-comment" aria-hidden="true"></i>50</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="blog_txt">
                                        <h1><a href="#"><%= @artigo.titulo %></a></h1>
                                        <div class="blog_txt_info">
                                            <ul>
                                                <li><%= @artigo.user.nome %></li>
                                                <li><%= @artigo.created_at.strftime('%d/%m/%Y') %></li>
                                            </ul>
                                        </div>
                                        <%= @artigo.texto.html_safe %>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                        <div class="row">
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    <!--blog section end-->

app/views/eventos/_form.html.erb
<%= simple_form_for(@evento) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :inicio %>
    <%= f.input :fim %>
    <%= f.input :nome %>
    <%= f.input :texto %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Eventos</h1>

<table>
  <thead>
    <tr>
      <th>Inicio</th>
      <th>Fim</th>
      <th>Nome</th>
      <th>Texto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.inicio %></td>
        <td><%= evento.fim %></td>
        <td><%= evento.nome %></td>
        <td><%= evento.texto %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New Evento</h1>

<%= render 'form', evento: @evento %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inicio:</strong>
  <%= @evento.inicio %>
</p>

<p>
  <strong>Fim:</strong>
  <%= @evento.fim %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @evento.nome %>
</p>

<p>
  <strong>Texto:</strong>
  <%= @evento.texto %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>

app/views/layouts/login.html.erb
<html lang="en">
  <head
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/icon" href="assets/faviconemt.jpeg" />

    <title>Admin | Espaço Médico</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.1/examples/sign-in/signin.css" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" action="/users/sign_in" method="post">
    <%= token_tag %>
      <%= image_tag('URSO_EDITADO.png', class: "mb-4", width: "150")%>
      <h4 class=" mb-3 font-weight-normal">Administrativo Espaço Médico</h4>
      <label for="inputEmail" class="sr-only">Email</label>
      <input type="email" id="inputEmail" name="user[email]" class="form-control" placeholder="Email" required autofocus>
      <label for="inputPassword" class="sr-only">Senha</label>
      <input type="password" name="user[password]" id="inputPassword" class="form-control" placeholder="Senha" required>
      <div class="checkbox mb-3">
        <label>
          <input name="user[remember_me]" type="checkbox" value="remember-me"> Lembrar
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
    </form>
  </body>
</html>

app/views/layouts/medic.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin | Espaço Médico</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" media="all" href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Admin</a>
            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/medic/allarticles">Artigos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/medic/newarticle">Novo Artigo</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users/edit">Meu perfil</a>
          </li>
          <li class="nav-item">
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class:'nav-link') %>        
          </li>
        </ul>
      </div>
    </nav>
        <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/register.html.erb
<html lang="en">
  <head
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/icon" href="assets/faviconemt.jpeg" />

    <title>Admin | Espaço Médico</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.1/examples/sign-in/signin.css" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" action="/users" method="post" enctype="multipart/form-data">
    <%= token_tag %>
      <%= image_tag('URSO_EDITADO.png', class: "mb-4", width: "150")%>
      <h4 class=" mb-3 font-weight-normal">Administrativo Espaço Médico</h4>
      <label for="inputEmail" class="sr-only">Email</label>
      <input type="email" id="inputEmail" name="user[email]" class="form-control" placeholder="Email" required autofocus>
      <label for="inputPassword" class="sr-only">Senha</label>
      <input type="password" name="user[password]" id="inputPassword" class="form-control" placeholder="Senha" required>
      <label for="inputEmail" class="sr-only">Nome</label>
      <input type="text" name="user[nome]" class="form-control" placeholder="Nome" required>
            <label for="inputEmail" class="sr-only">Especialidade</label>
      <input type="text" name="user[especialidade]" class="form-control" placeholder="Especialidade" required>
            <label for="inputEmail" class="sr-only">CRM</label>
      <input type="text" name="user[crm]" class="form-control" placeholder="CRM" required >
            <label for="inputEmail" class="sr-only">Resumo</label>
      <textarea name="user[resumo]" class="form-control" placeholder="Escreva um resumo sobre você" required></textarea>
      <label for="file" class="sr-only">Foto</label>
      <p>Insira sua foto</p>
      <input type="file" id="file" name="user[avatar]" class="form-control" placeholder="Insira sua foto" required >

      <div class="checkbox mb-3">
        <label>
          <input name="user[remember_me]" type="checkbox" value="remember-me"> Lembrar
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Cadastrar</button>
      <p style="margin-top: 30px;">&nbsp;</p>
    </form>
  </body>
</html>

app/views/pages/aboutus.html.erb
      <!--med_tittle_section-->
    <div class="med_tittle_section">
        <div class="med_img_overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="med_tittle_cont_wrapper">
                        <div class="med_tittle_cont">
                            <h1>Sobre </h1>
                            <ol class="breadcrumb">
                                <li><a href="index.html">Home</a>
                                </li>
                                <li>Sobre</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- med_tittle_section End -->
    <!--about us section start-->
    <div class="about_us_wrapper" style="background-color: #fff; padding-bottom: 30px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                    <div class="about_img">
                            <%= image_tag("TesteSobre.jpg", class: "image-responsive")%>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 med_toppadder70">
                    <div class="abt_heading_wrapper abt_2_heading">
                        <h1 class="med_bottompadder20">Espaço Médico Terê</h1>
                        <%= image_tag("line.png", class: "med_bottompadder20")%>
                        
                    </div>
                    <div class="abt_txt">
                        <h3>Cuidando de você e sua família com muito carinho e segurança.</h3>
                        <p class="med_toppadder20">O Espaço Médico Terê está localizado no coração de Teresópolis, no moderno Centro Empresarial Cosmopolitan Office. Contamos com salas equipadas para atendimento médico pediátrico e adulto. Com uma equipe profissional multidisciplinar, experiente e atenta as suas necessidades.</p>
                    </div>
                    <div class="abt_chk med_toppadder30">
                        <div class="content">
                            <ul>
                                <li><i class="fa fa-check-square-o" aria-hidden="true"></i><span>3 salas de atendimento</span>
                                </li>
                                <li><i class="fa fa-check-square-o" aria-hidden="true"></i><span>3 elevadores</span>
                                </li>
                                <li><i class="fa fa-check-square-o" aria-hidden="true"></i><span>Acessibilidade</span>
                                </li>
                                <li><i class="fa fa-check-square-o" aria-hidden="true"></i><span>Estacionamento</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="abt_heading_wrapper abt_2_heading_mn">
                        <h1 class="med_bottompadder20">Missão </h1>
                        <%= image_tag("line.png", class: "med_bottompadder20")%>
                    </div>
                    <div class="abt_txt">
                        <p class="med_toppadder20">Prestar serviços de saúde com muito amor para crianças,  adolescentes e adultos com ética, alta qualidade, conforto e segurança, buscando constantemente a atualização científica e tecnológica.</p>
                        <p class="med_toppadder10"><i>“Comprimidos aliviam a dor, mas só o amor alivia o sofrimento.”</i></p><p><i>Patch Adams - O Amor é Contagioso</i></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--about us section end-->

app/views/pages/medicallarticles.erb
<h1>Artigos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artigos.each do |artigo| %>
      <tr>
        <td><%= artigo.titulo %></td>
        <td><%= link_to 'Ver', artigo %></td>
        <td><%= link_to 'Editar', edit_artigo_path(artigo) %></td>
        <td><%= link_to 'Deletar', artigo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pages/medicnewarticle.erb
<main role="main" id="artigo" class="container" style="padding-top: 30px;">

<%= simple_form_for @artigo, html: {multipart: true} do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :titulo %>
    <div class="form-group file optional artigo_capa">
    <label class="file optional" for="artigo_capa">Adicione uma imagem ao artigo</label>
    <input class="form-control-file file optional" @change="onFileChange" type="file" name="artigo[capa]" id="artigo_capa">
    </div>
    <div style="max-width: 500px; max-height: 350px;">
    <img style="max-width: 300px; max-height: 260px;" v-if="url" :src="url" />
  </div>
   
  </div>
  <%= f.input :texto, as: :ckeditor, input_html: { ckeditor: { toolbar: 'mini' } } %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>


        

    </main><!-- /.container -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>